polyswarm/polyswarmd

- src/polyswarmd/eth.py
Fixes https://github.com/polyswarm/polyswarmd/issues/39
See the new msg returned below:
`{'status': 'FAIL', 'message': {'error': "{'code': -32000, 'message': 'nonce too low'}"}}
`
> catch nonce too low error and return failure msg

- scripts/wait_for_truffle.sh
- src/polyswarmd/__init__.py
- src/polyswarmd/balances.py
- src/polyswarmd/bounties.py
- src/polyswarmd/chains.py
- src/polyswarmd/config.py
- src/polyswarmd/eth.py
- src/polyswarmd/offers.py
- src/polyswarmd/relay.py
- src/polyswarmd/staking.py
- src/polyswarmd/utils.py
- src/polyswarmd/websockets.py
Adds a decorator (`@chain`) to all routes that need chain info. 
Usually it parses it from the request itself, but in some cases the chain is forced using `@chain(‘home’)`.
It attaches the addrs, web3, and contract bindings to the flask g proxy so the data is only available in the context of a request.
> Move sidechain handling to decorator

- src/polyswarmd/chains.py
In chains, I was using nonlocal chain_name to store the value if it wasn't specified in the argument. 
That resulted in the arg from the first command lasting through to the next.
Instead, that needed to be assigned to local variable.
> Stop editing chain_name directly which caused weird behavior.

- src/polyswarmd/bounties.py
Should help fix the assertion [error](https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22core_service%22%5D&event&from_ts=1540840223380&index=main&live=false&query=container_name%3Agamma_polyswarmd.1.%2A+status%3A%28error+OR+info+OR+warn%29&stream_sort=desc&to_ts=1540840226829) we see on restarts.
strangely the line below returns a huge number when using geth if the bounty doesn't exist when it should be reverted. This caused polyswarmd to loop forever
https://github.com/polyswarm/polyswarmd/blob/bb3dfa7897efac99e4f2f2b015693c907b01ee8d/src/polyswarmd/bounties.py#L342
> add check for empty bounty

- requirements.txt
Apparently stable is still vulnerable, bumping to pre-release.
> Bump to pre-release version of PyYAML

- src/polyswarmd/__main__.py
- src/polyswarmd/eth.py
Separate /transactions into GET and POST. 
The POST route returns a list of tx hashes and errors. 
The GET route returns a dict of list of events, or errors.
> Allow clients to recover from known transaction issues

- src/polyswarmd/__main__.py
- src/polyswarmd/config.py
- src/polyswarmd/wsgi.py
I think this might be an appropriate place to call our that polyswarmd is ready for service. It's immediately following config loads from consul.
> Print a ready message once server is ready

- requirements.txt
- setup.py
- src/polyswarmd/bounties.py
- src/polyswarmd/utils.py
Requires artifact_type when posing bounties. 
I thought about making this not required to avoid a breaking polyswarm-client change, but psc does checks against the decoded message, and it would reject any transactions with the artifact-type specified.
Also, extracts the artifact type from the bounty events, or when reading from the chain.
> Add artifact type to bounty

- src/polyswarmd/eth.py
Users of polyswarmd via integration testing should not be concerned with an inability to estimate gas. This should be under their threshold.
> Reduce WARNING to DEBUG

- requirements.txt
- src/polyswarmd/__init__.py
- src/polyswarmd/artifacts.py
- src/polyswarmd/bounties.py
- src/polyswarmd/websockets.py
Also, pulls the file from IPFS and reads metadata on websockets, and on get assertion routes. 
Rejects non conforming metadata to IPFS (but still allows to contract)
> Add route to upload metadata to IPFS

- src/polyswarmd/bounties.py
Retrieving the metadata from ipfs blocks the geth filter to websocket loop.
This adds a cache on the function that retrieves the metadata so doesn't block the loop on IO after the first time.
> Add LRU cache to function that takes an ipfs uri and returns the metadata

- .gitlab-ci.yml
Refactoring CI to have stages as:
Build -> Test -> Release -> Deploy
And jobs inside each stage run in parallel. This is built on top of the https://12factor.net/ philosophy.
- Master branch triggers releases for latest docker images
- Tags trigger releases for tagged docker images and pypi releases
- Build stages run on every push
TODO
- There are no tests for the image right now, and `tox` do not work without external services. Must check how to properly setup tests for this image.
> improved ci running in kubernetes, images pushed to aws

- src/polyswarmd/__init__.py
- src/polyswarmd/config.py
Address some observed performance issues on prod.
This PR does two main things:
1. Ensures that status checks fail if our HTTP sessions are hanging, rather than just checking for open ports. The downside to this is that it will restart `polyswarmd` if other services are not responding as well, but at this point `polyswarmd` is essentially non-functional anyway.
2. Increases the number of HTTP client workers, sets a low timeout, and lowers the number of retries so that hanging queries don't block execution.
> Lower timeout and retries, update status route

- src/polyswarmd/bounties.py
polyswarmd returns verdict values even when the engine did not reveal the assertion. While an accurate portrayal of the uint256 in the contract, it is confusing for anything that hits this endpoint. 
This change will return a list of nulls as verdict values when there was no reveal.
> Wipe the verdicts with None values when there was no reveal

- src/polyswarmd/artifacts.py
- src/polyswarmd/balances.py
- src/polyswarmd/bounties.py
- src/polyswarmd/chains.py
- src/polyswarmd/config.py
- src/polyswarmd/offers.py
- src/polyswarmd/relay.py
- src/polyswarmd/rpc.py
- src/polyswarmd/utils.py
- src/polyswarmd/websockets.py
After fooling around with Flask-SocketIO, and realizing the uwsgi integration isn't as good as we believed, I tried for the simpler, backwards compatible change that should get us the performance gains we wanted. 
This moves the filter polling loop into a long-running greenlet that broadcasts to all connected websockets. Because it has cross-greenlet communications with the main per connection greenlets we had to use some semaphores to protect the registered list. 
The main idea here is to only run at most a single greenlet per gunicorn worker. Once a websocket connects we establish the filters. We can't close the filters (from what I have seen) so if we drop down to 0 websockets, the next new connection will trigger a flush of existing filter changes that occurred before the websocket …
> Move Geth RPC to separate greenlet 

- src/polyswarmd/config.py
- src/polyswarmd/eth.py
`estimateGas` chews up a lot of `geth-rpc` time. Don't query this when the answer is 0.
> Stop estimating gas on free chains

- src/polyswarmd/artifacts.py
We increased the anonymous user upload limit, but didn't increase it here. This results in bounties that appear to hang indefinitely if the user isn't logged in.
> change to match portal-backend

- src/polyswarmd/monkey.py
While possibly necessary for 256 artifact bounties, causes lots of nonce desync issues.
> Decrease timeout again.

- src/polyswarmd/__init__.py
- src/polyswarmd/artifacts/artifacts.py
- src/polyswarmd/config.py
Removed hard coded anonymous & user sizes
Also, removes the flask MAX_CONTENT_LENGTH value, since we can't know the appropriate size going in.
> Read artifact size limits from api key mgmt

- src/polyswarmd/bounties.py
- src/polyswarmd/rpc.py
Fixes the issue where some engines metadata is a json string instead of decoded json.
> Attempt to load metadata even if stored directly on chain

- src/polyswarmd/eth.py
The timeout was too low to handle load once settles start coming in. Increased timeout by 6x. 
If someone gets to a state where they are sending too high of nonces it will take longer to recover, but it should stop all the spurious errors, which I think is a fair tradeoff.
> Increase get transaction timeout

- src/polyswarmd/__init__.py
- src/polyswarmd/eth.py
rlp decode is blocking, and caused the `/status` route to fail, and created backups in transactions. 
Use gevent threadpool we can continue to respond to other requests while decoding transactions to verify them
> Use threadpool executor on rlp decode

- src/polyswarmd/eth.py
We are just going to have to deal with the timeout errors. 
If we make this too high engines will not know that their assertion posted, despite the timeout. That means they will miss the reveal window.
> Revert larger timeout

- src/polyswarmd/monkey.py
Default is `os.cpu_count() * 5`
> Use default number of workers for web3 connections

- src/polyswarmd/__init__.py
This adds an environment variable `DISABLE_WEBSOCKETS` to disable websocket support. EthereumRpc filters are installed the first time that a request is made to the websocket endpoint, but since that endpoint will not be initialized, we don't need to disable any of that code path.
> Disable websocket via env var

- requirements.dev.txt
- requirements.txt
- src/polyswarmd/bounties.py
- src/polyswarmd/eth.py
- src/polyswarmd/event_message.py
- src/polyswarmd/offers.py
- src/polyswarmd/relay.py
- src/polyswarmd/rpc.py
- src/polyswarmd/staking.py
- src/polyswarmd/websockets/messages.py
@supernothing pointed out in an earlier PR how slow `jsonschema` could really be
(see: https://www.peterbe.com/plog/jsonschema-validate-10x-faster-in-python) and proposed a future change.
This commit is a crude first attempt to do just that by running an editor macro over the codebase to replace our existing `jsonschema` validators with new, much faster, compiled `fastjsonschema` validators.
This PR also includes a change in `eth.py` (line 432) that replaces `processReceipt`, but only processes one log at a time, instead of a whole transaction receipt.
> Switch to compiled fastjsonschemas

- src/polyswarmd/config/contract.py
- src/polyswarmd/config/polyswarmd.py
- src/polyswarmd/services/artifact/__init__.py
- src/polyswarmd/services/ethereum/__init__.py
- src/polyswarmd/utils/__init__.py
- src/polyswarmd/utils/utils.py
- src/polyswarmd/views/artifacts.py
- src/polyswarmd/websockets/conftest.py
- src/polyswarmd/websockets/filter.py
- src/polyswarmd/websockets/json_schema.py
- tests/conftest.py
- tests/fixtures/config/polyswarmd/polyswarmd.yml
- tests/test_balances.py
- tests/test_bounties.py
- tests/test_eth.py
- tests/test_event_message.py
- tests/test_relay.py
- tests/utils.py
@Rizato found a batch of issues running the latest test suite on Python 3.6 & E2E state causing unit test failures,  which this PR addresses the root of.
In addition, it contains some quality of life patches to `gevent.sleep` & `web3.contract.Contract` to make tests almost instantaneous & entirely runnable without requesting any remote services. Finally, it has some automatic changes from `make format` and generating explicit exports through `__all__` in `__init__.py`
It is a bit chaotic (two 3-way merges from branches stashed on Jan 15th, with upstream changes!), but it doesn't contain much that needs serious review. It's changes are almost entirely limited to tests and those which aren't are all `make format`, automatic conversion of unnamed imports to `__all__` or [a change the warning …
> Last-minute improvements to unit-test infrastructure & privately-discussed changes

- src/polyswarmd/views/bounties.py
Not sure which engine is doing this. Moving to exception log so we can track down what engine is causing this.
> Log more information when metadata cannot be loaded

- requirements.txt
1.3.2 broke from an unpinned dependency
> Update min polyswarm-artifact version
