polyswarm/polyswarmd

README.rst

Add some solutions to problems that may arise with nondescript error messages.

Add a couple common issues and the root cause.

---

polyswarmd.py

Add timeouts to all IPFS api calls

---

src/polyswarmd/utils.py

fixes https://github.com/polyswarm/contracts/issues/19

add bounty guid to quorum reached event

---

src/polyswarmd/utils.py

The quorum mask should be a bool list, like other int mask fields.

Turn quorum mask to bool list.

---

src/polyswarmd/__init__.py

Add eth_address to request log

---

src/polyswarmd/__init__.py

Will help tracking down errors in logs/datadog

Add response logging on error

---

src/polyswarmd/bounties.py
src/polyswarmd/utils.py

Bug description here -> https://github.com/polyswarm/consumer/issues/2

Fix for broken verdicts of more than one false

---

src/polyswarmd/utils.py

Retval doesn't exist until later.
Use bounty[4] instead.

Fix bounty_to_dict

---

src/polyswarmd/eth.py

fixes timeout error in orchestration

remove erroneous while loop

---

src/polyswarmd/bounties.py
src/polyswarmd/utils.py

Pairs with https://github.com/polyswarm/contracts/pull/56

Add routes to get contract data about votes and bloom

---

src/polyswarmd/chains.py

Per polyswarm/polyswarm-client#94 change default chain to side.

Switch default chain to side.

---

README.rst
src/polyswarmd/bounties.py
src/polyswarmd/eth.py
src/polyswarmd/utils.py
src/polyswarmd/websockets.py

Change arbiter verdicts to votes

---

src/polyswarmd/__init__.py
src/polyswarmd/chains.py
src/polyswarmd/db.py
src/polyswarmd/websockets.py

See polyswarm/api-key-management#11

Update auth methods to use new api key mgmt structures

---

src/polyswarmd/chains.py
src/polyswarmd/utils.py
src/polyswarmd/websockets.py

Changes to event parameters in contracts

---

src/polyswarmd/relay.py

add `/fees` route for relay

---

src/polyswarmd/__init__.py

Fix: Retrieve future result in before_request

---

src/polyswarmd/__init__.py

Fix: copypasta error

---

src/polyswarmd/artifacts.py

Check for 0 artifact uploads

---

docker/release/polyswarmd.yml
src/polyswarmd/artifacts.py
src/polyswarmd/config.py

Reads the field artifact_limit from consul or config file. 
Closes #151
* polyswarm/contractor#15
* polyswarm/infrastructure#110 
* polyswarm/orchestration#54

Add artifact limit

---

src/polyswarmd/eth.py

Closes #20 
This is incompatible with transacting with offer_multisig contracts, so if accepted should file a ticket to address that (doing so properly is complicated as not a fixed address)

Additional tx validation

---

src/polyswarmd/artifacts.py

Fix list_artifacts returning a response

---

src/polyswarmd/__init__.py
src/polyswarmd/monkey.py

Closes #169 
Alternative to #168

On connection error, retry request

---

requirements.txt
setup.py
src/polyswarmd/__init__.py
src/polyswarmd/config.py
src/polyswarmd/profiler.py

Uses https://github.com/polyswarm/flask-profiler/tree/profile-stats

Enable profiler for routes

---

requirements.txt

Addresses https://github.com/polyswarm/development-private/issues/246

Bump PyYAML to 3.13

---

src/polyswarmd/chains.py

Remove extra join

---

src/polyswarmd/artifacts.py

Reverts polyswarm/polyswarmd#188

Revert "Use index 0-255 for filename rather than original filename"

---

src/polyswarmd/utils.py
tests/test_utils.py

I wasn't able to run the unit tests locally immediately so either run the tests locally or let CI finish up before merging.

Simplified and removed dependencies of `to_padded_hex'

---

.gitlab-ci.yml

Using image variable

---

.gitlab-ci.yml

Working e2e tests. Pulls the image from the build stage and run against eicar engine sending a malicious and a non-malicious file. Wait for the bounty to finish.

new e2e tests

---

src/polyswarmd/__init__.py

Adjust some of the settings we made in the request pool based on stage testing.

tweak requests config based on testing

---

src/polyswarmd/artifacts/ipfs.py
src/polyswarmd/rpc.py
src/polyswarmd/utils.py
tests/test_utils.py

* Try to reduce slowdown with ipfs
* Reconnect filters with all variables
* Fix int to bool list with leading zeros

Fix errors found with multi artifact bounties

---

src/polyswarmd/artifacts/artifacts.py

Respect the order files are submitted.
Un-revert this pr https://github.com/polyswarm/polyswarmd/pull/190
Please check if this works @supernothing @Rizato

Respect artifact instance order in bounty

---

src/polyswarmd/__init__.py

Remove logs I put in to see state during e2e

Remove logs

---

requirements.txt
src/polyswarmd/artifacts/artifacts.py
src/polyswarmd/artifacts/ipfs.py
src/polyswarmd/bounties.py

Attempt to prevent the no path error when uploading files to ipfs

Switch to official ipfs http client

---

src/polyswarmd/utils.py

Remove address from deprecate event

---

src/polyswarmd/artifacts/ipfs.py
src/polyswarmd/eth.py

Trying to catch errors that would expand the transaction size. 
Among other fixes

Reduce likelihood of timeouts

---

src/polyswarmd/bounties.py
src/polyswarmd/config.py
src/polyswarmd/eth.py
src/polyswarmd/utils.py

* Add amount per artifact
* Add max bid on assertions

Support tweak marketplace contract changes

---

src/polyswarmd/websockets/filter.py
src/polyswarmd/websockets/messages.py

Also, made some changes to FilterWrapper because I was getting weakref errors locally

Use AssertionMetadata validation for reveals

---

src/polyswarmd/config.py
src/polyswarmd/eth.py
src/polyswarmd/websockets/message_types.py
src/polyswarmd/websockets/messages.py

Supports https://github.com/polyswarm/contractor/pull/79

Add Undeprecated event & add rollover to Deprecated

---

docker/Dockerfile
src/polyswarmd/event_message.py
src/polyswarmd/rpc.py
src/polyswarmd/websockets/filter.py
src/polyswarmd/websockets/message_types.py

Handle filter not found & restart filters after that error

Fix filter not found
